runtime: python311

env_variables:
  ENVIRONMENT: production
  JWT_SECRET: mysc-ir-platform-secret-2025

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 2