services:
  - type: web
    name: ir-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.index:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: MAX_FILE_SIZE
        value: "52428800"
      - key: MAX_TEXT_LENGTH  
        value: "50000"
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
    healthCheckPath: /api/health